name: Autolocker

on:
  pull_request_target:
    types: [closed]

permissions: write-all

jobs:
  autolock:
    #     if: ${{ github.event.pull_request.merged }} # Uncomment if you want it to run only when a PR gets MERGED
    runs-on: ubuntu-latest
    name: Autolocker
    steps:
      - name: Fetch running workflow runs
        id: fetch-workflow-runs
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${{ github.event.pull_request.head.ref }}&per_page=2")
          echo "response=$response" >> $env:GITHUB_OUTPUT

      - name: log the response
        run: |
          echo $steps.fetch-workflow-runs.outputs.response

      - name: Cancel the latest running or queued workflow on the current branch
        if: steps.fetch-workflow-runs.outputs.response != 'null'
        run: |
          latest_run_id=$(echo ${{ steps.fetch-workflow-runs.outputs.response }} | jq -r '.workflow_runs[] | select(.status == "in_progress" or .status == "queued" or .status == "requested" or .status == "waiting" or .status == "pending") | .id' | head -n 1)
          if [ -n "$latest_run_id" ]; then
            echo "Cancelling workflow run $latest_run_id"
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$latest_run_id/cancel"
          else
            echo "No running or queued workflows found on the current branch to cancel."
          fi
      - name: Autolock PRs that got merged or closed
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.lock({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              lock_reason: "resolved" // ["off-topic", "too heated", "resolved", "spam"]
            })
